name: adpro
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  universal_platform:
  animate_do:
  auto_size_text:
  flutter_animate:
  flutter_dotenv: ^5.0.2
  data_connection_checker: ^0.3.4
  permission_handler: ^10.2.0
  shimmer:
  flutter_phosphor_icons:
  flutter_screenutil:
  flutter_secure_storage:
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  intl: ^0.18.1
  logger: ^1.3.0
  rxdart: ^0.27.7
  freezed_annotation: ^2.2.0
  json_annotation:
  flutter_local_notifications:
  injectable: ^1.5.0
  get_it: ^7.2.0
  flutter_svg: ^2.0.5
  hive: ^2.2.3
  google_fonts: ^4.0.4
  bloc: ^8.1.1
  dio:
  shared_preferences: ^2.1.0
  carousel_slider: ^4.2.1
  badges: ^3.1.1
  page_transition: ^2.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: any
  flutter_gen: any
  flutter_gen_runner:
  freezed:
  json_serializable:
  injectable_generator:

flutter_gen:
  integrations:
    flutter_svg: true
    rive: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/png/
    - assets/fonts/
    - .env

  fonts:
    - family: Mark
      fonts:
        - asset: assets/fonts/Mark-font/Mark-Thin.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/Mark-font/Mark-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/Mark-font/Mark-Black.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Mark-font/Mark-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Mark-font/Mark-Bold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/Mark-font/Mark-Heavy.ttf
          weight: 700
          style: normal
